# Generated by Django 5.2.17 on 2026-09-24 09:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FictievePatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=100)),
                ('achternaam', models.CharField(max_length=100)),
                ('geboortedatum', models.DateField()),
                ('biologisch_geslacht', models.CharField(choices=[('vrouw', 'Vrouw'), ('man', 'Man'), ('anders', 'Anders')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('docent', 'Docent'), ('student', 'Student')], default='student', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BasisCasus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('opdracht_instructie', models.TextField()),
                ('publicatie_status', models.CharField(choices=[('verborgen', 'Verborgen'), ('open', 'Open')], default='verborgen', max_length=20)),
                ('inlever_deadline', models.DateTimeField()),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
                ('docent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basiscasussen', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='casus', to='epd.fictievepatient')),
            ],
            options={
                'ordering': ['-aangemaakt_op'],
            },
        ),
        migrations.CreateModel(
            name='StudentUitwerking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('gestart', 'Gestart'), ('ingeleverd', 'Ingeleverd'), ('beoordeeld', 'Beoordeeld')], default='gestart', max_length=20)),
                ('start_datum', models.DateTimeField(auto_now_add=True)),
                ('inlever_datum', models.DateTimeField(blank=True, null=True)),
                ('casus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uitwerkingen', to='epd.basiscasus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uitwerkingen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_datum'],
            },
        ),
        migrations.CreateModel(
            name='StudentUitwerkingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sjabloon_onderdeel_id', models.CharField(max_length=100)),
                ('waarde', models.JSONField(default=dict)),
                ('uitwerking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='epd.studentuitwerking')),
            ],
        ),
        migrations.CreateModel(
            name='BasisCasusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sjabloon_onderdeel_id', models.CharField(max_length=100)),
                ('waarde', models.JSONField(default=dict)),
                ('casus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='epd.basiscasus')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('casus', 'sjabloon_onderdeel_id'), name='unique_basis_data_component')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentuitwerking',
            constraint=models.UniqueConstraint(fields=('student', 'casus'), name='unique_student_casus'),
        ),
        migrations.AddConstraint(
            model_name='studentuitwerkingdata',
            constraint=models.UniqueConstraint(fields=('uitwerking', 'sjabloon_onderdeel_id'), name='unique_student_data_component'),
        ),
    ]
