# Generated by Django 5.2.17 on 2026-09-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basiscasus',
            name='afdeling',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='basiscasus',
            name='inleiding',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='basiscasus',
            name='leerdoelen',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='basiscasus',
            name='rol',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fictievepatient',
            name='context_beschrijving',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fictievepatient',
            name='foto_url',
            field=models.URLField(blank=True),
        ),
    ]
