# Generated by Django 5.2.17 on 2026-09-24 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0002_assignment_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='status',
        ),
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='learning_objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='module',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='kind',
            field=models.CharField(choices=[('information', 'Informatie'), ('questionnaire', 'Vragenlijst'), ('matrix', 'Matrix'), ('notes', 'Vrije notities')], default='notes', max_length=24),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='case', to='dossier.patient'),
        ),
        migrations.AlterField(
            model_name='case',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Docent'), ('student', 'Student')], default='student', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='epd_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Bezig'), ('submitted', 'Ingediend'), ('reviewed', 'Beoordeeld')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_cases', to='dossier.case')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dossier.module')),
                ('student_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_responses', to='dossier.studentcase')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'in te leveren'), ('submitted', 'ingediend'), ('resubmit', 'opnieuw inleveren'), ('approved', 'goedgekeurd')], default='todo', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='dossier.assignment')),
                ('student_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='dossier.studentcase')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studentcase',
            constraint=models.UniqueConstraint(fields=('case', 'student'), name='unique_student_case'),
        ),
        migrations.AddConstraint(
            model_name='moduleresponse',
            constraint=models.UniqueConstraint(fields=('student_case', 'module'), name='unique_module_response'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(fields=('student_case', 'assignment'), name='unique_assignment_submission'),
        ),
    ]
