# Generated by Django 5.2.17 on 2026-09-24 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def preserve_case_status(apps, schema_editor):
    Case = apps.get_model('dossier', 'Case')
    Case.objects.filter(published=True).update(status='published')


class Migration(migrations.Migration):

    dependencies = [
        ('dossier', '0003_remove_assignment_status_case_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentsubmission',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='moduleresponse',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='studentcase',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='module',
            name='has_children',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='phase',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='title',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='case',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Concept'), ('published', 'Gepubliceerd'), ('archived', 'Gearchiveerd')], default='draft', max_length=20),
        ),
        migrations.RunPython(preserve_case_status, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='case',
            name='published',
        ),
        migrations.AddField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='module',
            name='base_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='module',
            name='source_template_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moduleresponse',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moduleresponse',
            name='kind',
            field=models.CharField(choices=[('information', 'Informatie'), ('form', 'Formulier'), ('questionnaire', 'Vragenlijst'), ('matrix', 'Matrix'), ('notes', 'Vrije notities')], default='form', max_length=24),
        ),
        migrations.AddField(
            model_name='moduleresponse',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moduleresponse',
            name='schema',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='moduleresponse',
            name='title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Vrouw'), ('male', 'Man'), ('other', 'Anders'), ('unknown', 'Niet gespecificeerd')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentcase',
            name='case_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentcase',
            name='course',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentcase',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentcase',
            name='learning_objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentcase',
            name='patient_context',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='studentcase',
            name='patient_image',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='studentcase',
            name='patient_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentcase',
            name='patient_reference',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='studentcase',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcase',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='dossier.assignment'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(choices=[('todo', 'In te leveren'), ('submitted', 'Ingediend'), ('resubmit', 'Opnieuw inleveren'), ('approved', 'Goedgekeurd')], default='todo', max_length=20),
        ),
        migrations.AlterField(
            model_name='module',
            name='kind',
            field=models.CharField(choices=[('information', 'Informatie'), ('form', 'Formulier'), ('questionnaire', 'Vragenlijst'), ('matrix', 'Matrix'), ('notes', 'Vrije notities')], default='form', max_length=24),
        ),
        migrations.AlterField(
            model_name='moduleresponse',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='dossier.module'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Docent'), ('admin', 'Beheerder')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=80)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epd_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('module', 'Dossiermodule'), ('questionnaire', 'Vragenlijst'), ('matrix', 'Matrix')], max_length=24)),
                ('education', models.CharField(blank=True, max_length=120)),
                ('theme', models.CharField(blank=True, max_length=120)),
                ('instructions', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_fixed', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Actief'), ('archived', 'Gearchiveerd')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='library_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_copies', to='dossier.librarytemplate'),
        ),
        migrations.CreateModel(
            name='LibraryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=180)),
                ('key', models.SlugField(max_length=80)),
                ('field_type', models.CharField(choices=[('short_text', 'Korte tekst'), ('long_text', 'Vrije tekst'), ('number', 'Numeriek veld'), ('date', 'Datum'), ('datetime', 'Datum en tijd'), ('select', 'Keuzelijst'), ('observation', 'Observaties'), ('matrix', 'Matrix')], max_length=24)),
                ('help_text', models.CharField(blank=True, max_length=280)),
                ('required', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(blank=True, default=list)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dossier.librarytemplate')),
            ],
            options={
                'ordering': ['position', 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('template', 'key'), name='unique_library_field_key')],
            },
        ),
        migrations.CreateModel(
            name='ModuleField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=180)),
                ('key', models.SlugField(max_length=80)),
                ('field_type', models.CharField(choices=[('short_text', 'Korte tekst'), ('long_text', 'Vrije tekst'), ('number', 'Numeriek veld'), ('date', 'Datum'), ('datetime', 'Datum en tijd'), ('select', 'Keuzelijst'), ('observation', 'Observaties'), ('matrix', 'Matrix')], max_length=24)),
                ('help_text', models.CharField(blank=True, max_length=280)),
                ('required', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(blank=True, default=list)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='dossier.module')),
            ],
            options={
                'ordering': ['position', 'id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('module', 'key'), name='unique_module_field_key')],
            },
        ),
    ]
